/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.company.Frontend;

import com.company.Backend.*;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.IOException;
import java.util.List;

/**
 *
 * @author YOUSEF SHAWER
 */
public class DiffChooserGUI extends javax.swing.JFrame {

    /**
     * Creates new form DiffChooserGUI
     */

    public String sourceFile;
    private PersistenceManager pm;

    public String getSourceFile() {
        return sourceFile;
    }

    public DiffChooserGUI() {
        initComponents();
        PersistenceManager pm=new PersistenceManager();
        this.pm=pm;
        setLocationRelativeTo(null);

        try {
            pm.initializeFolders();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        SwingUtilities.invokeLater(this::loadCurrent);


    }
    private void loadCurrent(){
        if(pm.hasUnfinishedGame()){

            try {
                Game game = pm.loadCurrentGame();
                SudokuGame newGame= new SudokuGame(game.getGrid(),game.getDifficulty());
                newGame.setVisible(true);
                JOptionPane.showMessageDialog(null,"Loaded Current Game");
                this.dispose();

            } catch (IOException e) {
                JOptionPane.showMessageDialog(null,"error\n"+e);
            }


        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        EasyButton = new javax.swing.JButton();
        MedButton = new javax.swing.JButton();
        HardButton = new javax.swing.JButton();
        SourceButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Please Choose A Difficulty: ");

        EasyButton.setText("Easy");
        EasyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EasyButtonActionPerformed(evt);
            }
        });

        MedButton.setText("Medium");
        MedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedButtonActionPerformed(evt);
            }
        });

        HardButton.setText("Hard");
        HardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HardButtonActionPerformed(evt);
            }
        });

        SourceButton.setText("Source");
        SourceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SourceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addGap(126, 126, 126))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(MedButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(HardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EasyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SourceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(EasyButton)
                                .addGap(18, 18, 18)
                                .addComponent(MedButton)
                                .addGap(18, 18, 18)
                                .addComponent(HardButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                .addComponent(SourceButton)
                                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>

    private void SourceButtonActionPerformed(java.awt.event.ActionEvent evt) {

        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter= new FileNameExtensionFilter("CSV Files", "csv");
        chooser.setFileFilter(filter);
        chooser.setAcceptAllFileFilterUsed(false);
        int result= chooser.showOpenDialog(null);
        if(result== JFileChooser.APPROVE_OPTION){
            String filePath= chooser.getSelectedFile().getAbsolutePath();
            sourceFile=filePath;
            JOptionPane.showMessageDialog(null, filePath);

        }
        int[][] grid=Grid.getGrid(sourceFile);
        int[][] egrid=grid;
        int[][] mgrid=grid;
        int[][] hgrid=grid;

        RandomPairs randomPairs = new RandomPairs();
        List<int[]> cells=randomPairs.generateDistinctPairs(10);
        for(int[] p:cells){
            egrid[p[0]][p[1]]=0;
        }
        Game game1= new Game(egrid, GameConstants.Difficulty.EASY);
        try {
            pm.saveGame(GameConstants.Difficulty.EASY,game1);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        cells=randomPairs.generateDistinctPairs(20);
        for(int[] p:cells){
            egrid[p[0]][p[1]]=0;
        }
        Game game2= new Game(mgrid, GameConstants.Difficulty.MEDIUM);
        try {
            pm.saveGame(GameConstants.Difficulty.MEDIUM,game2);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        cells=randomPairs.generateDistinctPairs(25);
        for(int[] p:cells){
            egrid[p[0]][p[1]]=0;
        }
        Game game3= new Game(hgrid, GameConstants.Difficulty.HARD);
        try {
            pm.saveGame(GameConstants.Difficulty.HARD,game3);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }


    }

    private void EasyButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (!pm.hasGamesForAllLevels()){
            JOptionPane.showMessageDialog(null,"Please Choose a Source File!!");
        }
        else {
            try {
                Game game =pm.loadRandomGame(GameConstants.Difficulty.EASY);
                pm.saveCurrentGame(game);
                SudokuGame newGame= new SudokuGame(game.getGrid(), GameConstants.Difficulty.EASY);
                newGame.setVisible(true);
            } catch (Exception e) {
                throw new RuntimeException(e);
            }

            this.dispose();
        }

    }

    private void MedButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (!pm.hasGamesForAllLevels()){
            JOptionPane.showMessageDialog(null,"Please Choose a Source File!!");
        }
        else {
            try {
                Game game =pm.loadRandomGame(GameConstants.Difficulty.MEDIUM);
                pm.saveCurrentGame(game);
                SudokuGame newGame= new SudokuGame(game.getGrid(), GameConstants.Difficulty.MEDIUM);
                newGame.setVisible(true);
            } catch (Exception e) {
                throw new RuntimeException(e);
            }

            this.dispose();
        }
    }

    private void HardButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (!pm.hasGamesForAllLevels()){
            JOptionPane.showMessageDialog(null,"Please Choose a Source File!!");
        }
        else {
            try {
                Game game =pm.loadRandomGame(GameConstants.Difficulty.HARD);
                pm.saveCurrentGame(game);
                SudokuGame newGame= new SudokuGame(game.getGrid(), GameConstants.Difficulty.HARD);
                newGame.setVisible(true);
            } catch (Exception e) {
                throw new RuntimeException(e);
            }

            this.dispose();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiffChooserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiffChooserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiffChooserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiffChooserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiffChooserGUI().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton EasyButton;
    private javax.swing.JButton HardButton;
    private javax.swing.JButton MedButton;
    private javax.swing.JButton SourceButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration
}
